name: S3 Website Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check AWS Cli version
        run: aws --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync ./ s3://s3-cloudresume-aadhith/ --exclude ".git/*" --exclude ".github/*" --exclude "README.md" --delete

      - name: Refresh Cloudfront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1N2XDF0SGMG24 --paths "/*"
